import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Module 1: ROS2 Nervous System',
      items: [
        'module1/chapter1-introduction',
        'module1/chapter2-nodes-topics-services',
        'module1/chapter3-rclpy',
        'module1/chapter4-urdf',
        'module1/chapter5-final-project',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin (Gazebo & Unity)',
      items: ['module2/overview'],
    },
    {
      type: 'category',
      label: 'Module 3: AI Robot Brain (NVIDIA Isaac)',
      items: ['module3/overview'],
    },
    {
      type: 'category',
      label: 'Module 4: Vision Language Action (VLA)',
      items: ['module4/overview'],
    },
  ],
};

export default sidebars;
